/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenprojectsir;

/**
 *
 * @author fabri
 */
public class EditFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditFrame
     */
    private Televisor t1;
    
    public EditFrame(Televisor t2) {
        initComponents();
        t1 = t2;
        
        checkBoxBotoneraEditar.setSelected(t1.isBotonera());
        checkBoxPanelEditar.setSelected(t1.isPanel());
        checkBoxMainEditar.setSelected(t1.isMain());
        checkBoxBacklightEditar.setSelected(t1.isBacklight());
        checkBoxFuenteEditar.setSelected(t1.isFuente());
        checkBoxMonoplacaEditar.setSelected(t1.isMonoplaca());
        checkBoxModuloWifiEditar.setSelected(t1.isModuloWifi());
        checkBoxInverterEditar.setSelected(t1.isInverter());
        checkBoxTconEditar.setSelected(t1.isTcon());
        checkBoxParlantesEditar.setSelected(t1.isParlantes());
        checkBoxPatasEditar.setSelected(t1.isPanel());
        checkBoxBaseEditar.setSelected(t1.isBase());
        checkBoxSensorRemotoEditar.setSelected(t1.isSensorRemoto());  
        
    }

    public Televisor devolverValores(Televisor t1){

        t1.setBotonera(checkBoxBotoneraEditar.isSelected());
        t1.setPanel(checkBoxPanelEditar.isSelected());
        t1.setMain(checkBoxMainEditar.isSelected());
        t1.setBacklight(checkBoxBacklightEditar.isSelected());
        t1.setFuente(checkBoxFuenteEditar.isSelected());
        t1.setMonoplaca(checkBoxMonoplacaEditar.isSelected());
        t1.setModuloWifi(checkBoxModuloWifiEditar.isSelected());
        t1.setInverter(checkBoxInverterEditar.isSelected());
        t1.setTcon(checkBoxTconEditar.isSelected());
        t1.setParlantes(checkBoxParlantesEditar.isSelected());
        t1.setPatas(checkBoxPatasEditar.isSelected());
        t1.setBase(checkBoxBaseEditar.isSelected());
        t1.setSensorRemoto(checkBoxSensorRemotoEditar.isSelected());

        return t1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        componentesPanelEditar = new javax.swing.JPanel();
        checkBoxFuenteEditar = new javax.swing.JCheckBox();
        checkBoxBacklightEditar = new javax.swing.JCheckBox();
        checkBoxPanelEditar = new javax.swing.JCheckBox();
        checkBoxTconEditar = new javax.swing.JCheckBox();
        checkBoxModuloWifiEditar = new javax.swing.JCheckBox();
        checkBoxMonoplacaEditar = new javax.swing.JCheckBox();
        checkBoxInverterEditar = new javax.swing.JCheckBox();
        checkBoxBotoneraEditar = new javax.swing.JCheckBox();
        checkBoxMainEditar = new javax.swing.JCheckBox();
        checkBoxParlantesEditar = new javax.swing.JCheckBox();
        checkBoxSensorRemotoEditar = new javax.swing.JCheckBox();
        checkBoxPatasEditar = new javax.swing.JCheckBox();
        checkBoxBaseEditar = new javax.swing.JCheckBox();
        buttonAceptarEditar = new javax.swing.JButton();
        componentesLabelEditar = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setTitle("Editar");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        checkBoxFuenteEditar.setText("fuente");
        checkBoxFuenteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxFuenteEditarActionPerformed(evt);
            }
        });

        checkBoxBacklightEditar.setText("backlight");
        checkBoxBacklightEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxBacklightEditarActionPerformed(evt);
            }
        });

        checkBoxPanelEditar.setText("panel");

        checkBoxTconEditar.setText("tcon");

        checkBoxModuloWifiEditar.setText("placa wifi");

        checkBoxMonoplacaEditar.setText("monoplaca");
        checkBoxMonoplacaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMonoplacaEditarActionPerformed(evt);
            }
        });

        checkBoxInverterEditar.setText("inverter");

        checkBoxBotoneraEditar.setText("botonera");

        checkBoxMainEditar.setText("main");
        checkBoxMainEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMainEditarActionPerformed(evt);
            }
        });

        checkBoxParlantesEditar.setText("parlantes");

        checkBoxSensorRemotoEditar.setText("sensor remoto");

        checkBoxPatasEditar.setText("patas");

        checkBoxBaseEditar.setText("base");

        buttonAceptarEditar.setText("aceptar");
        buttonAceptarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout componentesPanelEditarLayout = new javax.swing.GroupLayout(componentesPanelEditar);
        componentesPanelEditar.setLayout(componentesPanelEditarLayout);
        componentesPanelEditarLayout.setHorizontalGroup(
            componentesPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentesPanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(componentesPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(componentesPanelEditarLayout.createSequentialGroup()
                        .addComponent(checkBoxMonoplacaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxTconEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxSensorRemotoEditar))
                    .addGroup(componentesPanelEditarLayout.createSequentialGroup()
                        .addComponent(checkBoxMainEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxBotoneraEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxModuloWifiEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(componentesPanelEditarLayout.createSequentialGroup()
                        .addComponent(checkBoxFuenteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxInverterEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxParlantesEditar))
                    .addGroup(componentesPanelEditarLayout.createSequentialGroup()
                        .addGroup(componentesPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxBacklightEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBoxPatasEditar))
                        .addGap(18, 18, 18)
                        .addGroup(componentesPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxPanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(componentesPanelEditarLayout.createSequentialGroup()
                                .addComponent(checkBoxBaseEditar)
                                .addGap(53, 53, 53)
                                .addComponent(buttonAceptarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        componentesPanelEditarLayout.setVerticalGroup(
            componentesPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentesPanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(componentesPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxMainEditar)
                    .addComponent(checkBoxBotoneraEditar)
                    .addComponent(checkBoxModuloWifiEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(componentesPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxFuenteEditar)
                    .addComponent(checkBoxInverterEditar)
                    .addComponent(checkBoxParlantesEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(componentesPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxMonoplacaEditar)
                    .addComponent(checkBoxTconEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxSensorRemotoEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(componentesPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxBacklightEditar)
                    .addComponent(checkBoxPanelEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(componentesPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxPatasEditar)
                    .addComponent(checkBoxBaseEditar)
                    .addComponent(buttonAceptarEditar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        componentesLabelEditar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        componentesLabelEditar.setText("Componentes disponibles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(componentesLabelEditar)
                    .addComponent(componentesPanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(componentesLabelEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentesPanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxFuenteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxFuenteEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxFuenteEditarActionPerformed

    private void checkBoxBacklightEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxBacklightEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxBacklightEditarActionPerformed

    private void checkBoxMonoplacaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMonoplacaEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxMonoplacaEditarActionPerformed

    private void checkBoxMainEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMainEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxMainEditarActionPerformed

    private void buttonAceptarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptarEditarActionPerformed
        // TODO add your handling code here:
        t1.setBotonera(checkBoxBotoneraEditar.isSelected());
        t1.setPanel(checkBoxPanelEditar.isSelected());
        t1.setMain(checkBoxMainEditar.isSelected());
        t1.setBacklight(checkBoxBacklightEditar.isSelected());
        t1.setFuente(checkBoxFuenteEditar.isSelected());
        t1.setMonoplaca(checkBoxMonoplacaEditar.isSelected());
        t1.setModuloWifi(checkBoxModuloWifiEditar.isSelected());
        t1.setInverter(checkBoxInverterEditar.isSelected());
        t1.setTcon(checkBoxTconEditar.isSelected());
        t1.setParlantes(checkBoxParlantesEditar.isSelected());
        t1.setPatas(checkBoxPatasEditar.isSelected());
        t1.setBase(checkBoxBaseEditar.isSelected());
        t1.setSensorRemoto(checkBoxSensorRemotoEditar.isSelected());
        setVisible(false);   
    }//GEN-LAST:event_buttonAceptarEditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAceptarEditar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBoxBacklightEditar;
    private javax.swing.JCheckBox checkBoxBaseEditar;
    private javax.swing.JCheckBox checkBoxBotoneraEditar;
    private javax.swing.JCheckBox checkBoxFuenteEditar;
    private javax.swing.JCheckBox checkBoxInverterEditar;
    private javax.swing.JCheckBox checkBoxMainEditar;
    private javax.swing.JCheckBox checkBoxModuloWifiEditar;
    private javax.swing.JCheckBox checkBoxMonoplacaEditar;
    private javax.swing.JCheckBox checkBoxPanelEditar;
    private javax.swing.JCheckBox checkBoxParlantesEditar;
    private javax.swing.JCheckBox checkBoxPatasEditar;
    private javax.swing.JCheckBox checkBoxSensorRemotoEditar;
    private javax.swing.JCheckBox checkBoxTconEditar;
    private javax.swing.JLabel componentesLabelEditar;
    private javax.swing.JPanel componentesPanelEditar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    // End of variables declaration//GEN-END:variables
}
